### ISSUE TITLE
[PE-D][Tester B] Reset/Delete Medicine History

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-1/tp#140]
Should be an option for users. Reasoning:

1) For consistency with diagnosis history and symptoms

2) If the user accumulates many entries over long-time usage of DrDuke, their medicine history will become needlessly cluttered with entries from many years ago, unlikely to be useful in the present.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jared-ee/ped#6

**Comment by Jeraldchen** [comment]
The intent of our application is to complement and ease the process of accessing healthcare at a lower severity level. Just like all other personal health records in other government applications like healthhub or the SAF eHealth system, users are not allowed to delete their medical history since healthcare providers are bounded by the law to retain such information. Our group will update the user guide more specifically to address this issue. Thank you for your feedback!
